# Generated by Django 4.0.6 on 2022-11-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_newproducts_title_newproducts_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproducts',
            name='trend',
        ),
    ]
