# Generated by Django 4.0.6 on 2022-11-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_newproducts_trend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproducts',
            name='type_gold',
        ),
    ]
