# Generated by Django 4.0.6 on 2022-11-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_newproducts_type_gold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='trend',
        ),
    ]
