# Generated by Django 4.0.6 on 2022-11-15 04:52

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_products_banner_date_create_brand_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_percent',
            field=models.BooleanField(default=False, verbose_name=blog.models.Discount),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='sale_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
