# Generated by Django 4.0.6 on 2022-11-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_products_discount_percent_products_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sale_price',
            field=models.IntegerField(null=True),
        ),
    ]
