# Generated by Django 4.0.6 on 2022-11-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_products_price_alter_products_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='products',
            name='discount_percent',
            field=models.ManyToManyField(to='blog.discount'),
        ),
    ]
