# Generated by Django 4.0.6 on 2022-11-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_trend_products_trend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='trend',
            new_name='trends',
        ),
    ]
