# Generated by Django 4.0.6 on 2022-11-15 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_trend_products_trends'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trend',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
