# Generated by Django 4.0.6 on 2022-11-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_trend_category_trend_date_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='trends',
        ),
        migrations.AddField(
            model_name='discountpage',
            name='trend',
            field=models.ManyToManyField(to='blog.discount'),
        ),
        migrations.DeleteModel(
            name='Trend',
        ),
    ]
