# Generated by Django 4.0.6 on 2022-11-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_trend_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='news',
        ),
        migrations.AddField(
            model_name='discount',
            name='new_rings',
            field=models.ManyToManyField(to='blog.trend'),
        ),
        migrations.DeleteModel(
            name='DiscountPage',
        ),
    ]
