# Generated by Django 4.0.6 on 2022-11-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_products_news_discount_new_rings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='new_rings',
        ),
        migrations.AddField(
            model_name='discount',
            name='new_rings',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Trend',
        ),
    ]
