# Generated by Django 4.0.6 on 2022-11-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_discount_new_rings_discount_new_rings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='new_rings',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
