# Generated by Django 4.0.6 on 2022-11-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_discount_new_rings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='detail/%y/%m/%d')),
                ('price', models.PositiveIntegerField()),
                ('base_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='product_detail',
            field=models.ManyToManyField(to='blog.detail'),
        ),
    ]
