# Generated by Django 4.0.6 on 2022-11-16 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_discount_product_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='product_detail',
        ),
        migrations.AddField(
            model_name='discount',
            name='is_discount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='blog.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_detail',
            field=models.ManyToManyField(blank=True, to='blog.detail'),
        ),
    ]
