# Generated by Django 4.0.6 on 2022-11-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_discount_product_detail_discount_is_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='is_discount',
        ),
        migrations.AddField(
            model_name='products',
            name='is_discount',
            field=models.BooleanField(default=True),
        ),
    ]
