# Generated by Django 4.0.6 on 2022-11-16 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_remove_products_product_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
    ]
