# Generated by Django 4.0.6 on 2022-11-16 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_remove_products_brand_alter_products_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_detail',
        ),
    ]
