# Generated by Django 4.0.6 on 2022-11-16 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_material_products_material_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='material_product',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
