# Generated by Django 4.0.6 on 2022-11-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_remove_products_material_product_delete_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='detail',
            field=models.ManyToManyField(to='blog.detail'),
        ),
    ]
