# Generated by Django 4.0.6 on 2022-11-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_products_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='material',
            field=models.ManyToManyField(to='blog.extramaterial'),
        ),
        migrations.AddField(
            model_name='extramaterial',
            name='material',
            field=models.ManyToManyField(to='blog.material'),
        ),
        migrations.AddField(
            model_name='products',
            name='materials',
            field=models.ManyToManyField(to='blog.material'),
        ),
    ]
