# Generated by Django 4.0.6 on 2022-11-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_discount_material_extramaterial_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='base_count',
        ),
        migrations.AddField(
            model_name='banner',
            name='chegirmalar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
